/*==============================================================================
 Project    : HRM_PRO
 File       : hrm_lookup_types.sql
 Object     : Seed Data - HRM_LOOKUP_TYPES
 Author     : Hany Shaker
 Created    : 2026-08-09
 Version    : 1.0

 Description:
     Initial lookup categories required by the HRM_PRO application.

 Notes:
     - Do not hard-code lookup IDs.
     - IDs are generated by the database sequence/trigger.
     - MERGE is used so the script can safely be executed more than once.

==============================================================================*/

MERGE INTO HRM_LOOKUP_TYPES tgt
USING
(
    SELECT
        'GENDER' AS LOOKUP_TYPE_CODE,
        'Gender' AS LOOKUP_TYPE_NAME,
        'Employee gender' AS DESCRIPTION,
        10 AS DISPLAY_SEQUENCE
    FROM DUAL

    UNION ALL

    SELECT
        'EMP_STATUS',
        'Employee Status',
        'Employee employment status',
        20
    FROM DUAL

    UNION ALL

    SELECT
        'LEAVE_TYPE',
        'Leave Type',
        'Types of employee leave',
        30
    FROM DUAL

    UNION ALL

    SELECT
        'ATT_STATUS',
        'Attendance Status',
        'Employee attendance status',
        40
    FROM DUAL

) src
ON
(
    tgt.LOOKUP_TYPE_CODE = src.LOOKUP_TYPE_CODE
)

WHEN MATCHED THEN

    UPDATE SET
        tgt.LOOKUP_TYPE_NAME = src.LOOKUP_TYPE_NAME,
        tgt.DESCRIPTION      = src.DESCRIPTION,
        tgt.DISPLAY_SEQUENCE  = src.DISPLAY_SEQUENCE,
        tgt.ACTIVE_YN         = 'Y'

WHEN NOT MATCHED THEN

    INSERT
    (
        LOOKUP_TYPE_CODE,
        LOOKUP_TYPE_NAME,
        DESCRIPTION,
        DISPLAY_SEQUENCE,
        ACTIVE_YN
    )
    VALUES
    (
        src.LOOKUP_TYPE_CODE,
        src.LOOKUP_TYPE_NAME,
        src.DESCRIPTION,
        src.DISPLAY_SEQUENCE,
        'Y'
    );

COMMIT;
