/*==============================================================================
 Project    : HRM_PRO
 File       : hrm_employees.sql
 Object     : Seed/Test Data - HRM_EMPLOYEES
 Author     : Hany Shaker
 Created    : 2026-08-10
 Version    : 1.0

 Description:
     Demo employees for HRM_PRO development/testing.

 Notes:
     - EMPLOYEE_ID is generated by TRG_HRM_EMPLOYEES_BIU.
     - Department and Job are resolved by business codes.
     - Gender and Employment Status are resolved by lookup codes.
     - MERGE makes the script safely re-runnable.

==============================================================================*/


MERGE INTO HRM_EMPLOYEES tgt
USING
(
    SELECT
        'EMP0001' AS EMPLOYEE_NO,
        'Ahmed' AS FIRST_NAME,
        'Mohamed' AS MIDDLE_NAME,
        'Ali' AS LAST_NAME,

        'أحمد' AS FIRST_NAME_AR,
        'محمد' AS MIDDLE_NAME_AR,
        'علي' AS LAST_NAME_AR,

        (
            SELECT l.LOOKUP_ID
            FROM HRM_LOOKUPS l
            JOIN HRM_LOOKUP_TYPES t
              ON t.LOOKUP_TYPE_ID = l.LOOKUP_TYPE_ID
            WHERE t.LOOKUP_TYPE_CODE = 'GENDER'
              AND l.LOOKUP_CODE = 'M'
        ) AS GENDER_ID,

        DATE '1985-05-10' AS DATE_OF_BIRTH,

        '28505101234567' AS NATIONAL_ID,

        (
            SELECT DEPARTMENT_ID
            FROM HRM_DEPARTMENTS
            WHERE DEPARTMENT_CODE = 'IT'
        ) AS DEPARTMENT_ID,

        (
            SELECT JOB_ID
            FROM HRM_JOBS
            WHERE JOB_CODE = 'SWDEV'
        ) AS JOB_ID,

        DATE '2020-01-15' AS HIRE_DATE,

        (
            SELECT l.LOOKUP_ID
            FROM HRM_LOOKUPS l
            JOIN HRM_LOOKUP_TYPES t
              ON t.LOOKUP_TYPE_ID = l.LOOKUP_TYPE_ID
            WHERE t.LOOKUP_TYPE_CODE = 'EMP_STATUS'
              AND l.LOOKUP_CODE = 'ACTIVE'
        ) AS EMP_STATUS_ID

    FROM DUAL

    UNION ALL

    SELECT
        'EMP0002',
        'Mona',
        'Ahmed',
        'Hassan',

        'منى',
        'أحمد',
        'حسن',

        (
            SELECT l.LOOKUP_ID
            FROM HRM_LOOKUPS l
            JOIN HRM_LOOKUP_TYPES t
              ON t.LOOKUP_TYPE_ID = l.LOOKUP_TYPE_ID
            WHERE t.LOOKUP_TYPE_CODE = 'GENDER'
              AND l.LOOKUP_CODE = 'F'
        ),

        DATE '1990-08-22',

        '29008221234567',

        (
            SELECT DEPARTMENT_ID
            FROM HRM_DEPARTMENTS
            WHERE DEPARTMENT_CODE = 'HR'
        ),

        (
            SELECT JOB_ID
            FROM HRM_JOBS
            WHERE JOB_CODE = 'HR_OFFICER'
        ),

        DATE '2021-03-01',

        (
            SELECT l.LOOKUP_ID
            FROM HRM_LOOKUPS l
            JOIN HRM_LOOKUP_TYPES t
              ON t.LOOKUP_TYPE_ID = l.LOOKUP_TYPE_ID
            WHERE t.LOOKUP_TYPE_CODE = 'EMP_STATUS'
              AND l.LOOKUP_CODE = 'ACTIVE'
        )

    FROM DUAL

    UNION ALL

    SELECT
        'EMP0003',
        'Omar',
        'Ali',
        'Hassan',

        'عمر',
        'علي',
        'حسن',

        (
            SELECT l.LOOKUP_ID
            FROM HRM_LOOKUPS l
            JOIN HRM_LOOKUP_TYPES t
              ON t.LOOKUP_TYPE_ID = l.LOOKUP_TYPE_ID
            WHERE t.LOOKUP_TYPE_CODE = 'GENDER'
              AND l.LOOKUP_CODE = 'M'
        ),

        DATE '1978-12-03',

        '27812031234567',

        (
            SELECT DEPARTMENT_ID
            FROM HRM_DEPARTMENTS
            WHERE DEPARTMENT_CODE = 'FIN'
        ),

        (
            SELECT JOB_ID
            FROM HRM_JOBS
            WHERE JOB_CODE = 'ACCOUNTANT'
        ),

        DATE '2015-06-15',

        (
            SELECT l.LOOKUP_ID
            FROM HRM_LOOKUPS l
            JOIN HRM_LOOKUP_TYPES t
              ON t.LOOKUP_TYPE_ID = l.LOOKUP_TYPE_ID
            WHERE t.LOOKUP_TYPE_CODE = 'EMP_STATUS'
              AND l.LOOKUP_CODE = 'ACTIVE'
        )

    FROM DUAL

) src
ON
(
    tgt.EMPLOYEE_NO = src.EMPLOYEE_NO
)

WHEN MATCHED THEN

    UPDATE SET
        tgt.FIRST_NAME      = src.FIRST_NAME,
        tgt.MIDDLE_NAME     = src.MIDDLE_NAME,
        tgt.LAST_NAME       = src.LAST_NAME,
        tgt.FIRST_NAME_AR   = src.FIRST_NAME_AR,
        tgt.MIDDLE_NAME_AR  = src.MIDDLE_NAME_AR,
        tgt.LAST_NAME_AR    = src.LAST_NAME_AR,
        tgt.GENDER_ID       = src.GENDER_ID,
        tgt.DATE_OF_BIRTH   = src.DATE_OF_BIRTH,
        tgt.NATIONAL_ID     = src.NATIONAL_ID,
        tgt.DEPARTMENT_ID   = src.DEPARTMENT_ID,
        tgt.JOB_ID          = src.JOB_ID,
        tgt.HIRE_DATE       = src.HIRE_DATE,
        tgt.EMP_STATUS_ID   = src.EMP_STATUS_ID,
        tgt.ACTIVE_YN       = 'Y'

WHEN NOT MATCHED THEN

    INSERT
    (
        EMPLOYEE_NO,
        FIRST_NAME,
        MIDDLE_NAME,
        LAST_NAME,
        FIRST_NAME_AR,
        MIDDLE_NAME_AR,
        LAST_NAME_AR,
        GENDER_ID,
        DATE_OF_BIRTH,
        NATIONAL_ID,
        DEPARTMENT_ID,
        JOB_ID,
        HIRE_DATE,
        EMP_STATUS_ID,
        ACTIVE_YN
    )
    VALUES
    (
        src.EMPLOYEE_NO,
        src.FIRST_NAME,
        src.MIDDLE_NAME,
        src.LAST_NAME,
        src.FIRST_NAME_AR,
        src.MIDDLE_NAME_AR,
        src.LAST_NAME_AR,
        src.GENDER_ID,
        src.DATE_OF_BIRTH,
        src.NATIONAL_ID,
        src.DEPARTMENT_ID,
        src.JOB_ID,
        src.HIRE_DATE,
        src.EMP_STATUS_ID,
        'Y'
    );


COMMIT;
