/*==============================================================================
 Project    : HRM_PRO
 File       : hrm_jobs.sql
 Object     : Seed Data - HRM_JOBS
 Author     : Hany Shaker
 Created    : 2026-08-10
 Version    : 1.0

 Description:
     Initial job definitions required by the HRM_PRO application.

 Notes:
     - JOB_ID is generated by TRG_HRM_JOBS_BIU.
     - JOB_CODE is the business identifier.
     - MERGE makes this script safely re-runnable.

==============================================================================*/


MERGE INTO HRM_JOBS tgt
USING
(
    SELECT
        'SWDEV' AS JOB_CODE,
        'Software Developer' AS JOB_TITLE,
        'مطور برمجيات' AS JOB_TITLE_AR,
        'Develops and maintains software applications.' AS DESCRIPTION
    FROM DUAL

    UNION ALL

    SELECT
        'DBA',
        'Database Administrator',
        'مسؤول قواعد البيانات',
        'Manages and maintains database systems.'
    FROM DUAL

    UNION ALL

    SELECT
        'ORACLE_CONS',
        'Oracle Consultant',
        'استشاري أوراكل',
        'Provides Oracle database and application consulting services.'
    FROM DUAL

    UNION ALL

    SELECT
        'HRMGR',
        'HR Manager',
        'مدير الموارد البشرية',
        'Manages human resources activities and policies.'
    FROM DUAL

    UNION ALL

    SELECT
        'HR_OFFICER',
        'HR Officer',
        'مسؤول موارد بشرية',
        'Handles HR administrative and employee-related activities.'
    FROM DUAL

    UNION ALL

    SELECT
        'ACCOUNTANT',
        'Accountant',
        'محاسب',
        'Handles accounting and financial transactions.'
    FROM DUAL

    UNION ALL

    SELECT
        'FIN_MGR',
        'Finance Manager',
        'مدير مالي',
        'Manages financial operations and reporting.'
    FROM DUAL

    UNION ALL

    SELECT
        'ADMIN_OFF',
        'Administrative Officer',
        'مسؤول إداري',
        'Handles administrative and office activities.'
    FROM DUAL

    UNION ALL

    SELECT
        'OPS_MGR',
        'Operations Manager',
        'مدير العمليات',
        'Manages operational activities and resources.'
    FROM DUAL

) src
ON
(
    tgt.JOB_CODE = src.JOB_CODE
)

WHEN MATCHED THEN

    UPDATE SET
        tgt.JOB_TITLE   = src.JOB_TITLE,
        tgt.JOB_TITLE_AR = src.JOB_TITLE_AR,
        tgt.DESCRIPTION = src.DESCRIPTION,
        tgt.ACTIVE_YN   = 'Y'

WHEN NOT MATCHED THEN

    INSERT
    (
        JOB_CODE,
        JOB_TITLE,
        JOB_TITLE_AR,
        DESCRIPTION,
        ACTIVE_YN
    )
    VALUES
    (
        src.JOB_CODE,
        src.JOB_TITLE,
        src.JOB_TITLE_AR,
        src.DESCRIPTION,
        'Y'
    );


COMMIT;
