/*==============================================================================
 Project    : HRM_PRO
 File       : hrm_departments.sql
 Object     : Seed Data - HRM_DEPARTMENTS
 Author     : Hany Shaker
 Created    : 2026-08-10
 Version    : 1.0

 Description:
     Initial departments required by the HRM_PRO application.

 Notes:
     - DEPARTMENT_ID is generated by the database trigger.
     - DEPARTMENT_CODE is the business identifier.
     - MERGE makes this script safely re-runnable.

==============================================================================*/


MERGE INTO HRM_DEPARTMENTS tgt
USING
(
    SELECT
        'IT' AS DEPARTMENT_CODE,
        'Information Technology' AS DEPARTMENT_NAME,
        'تكنولوجيا المعلومات' AS DEPARTMENT_NAME_AR,
        'Information Technology Department' AS DESCRIPTION
    FROM DUAL

    UNION ALL

    SELECT
        'HR',
        'Human Resources',
        'الموارد البشرية',
        'Human Resources Department'
    FROM DUAL

    UNION ALL

    SELECT
        'FIN',
        'Finance',
        'المالية',
        'Finance Department'
    FROM DUAL

    UNION ALL

    SELECT
        'ADMIN',
        'Administration',
        'الشئون الإدارية',
        'Administration Department'
    FROM DUAL

    UNION ALL

    SELECT
        'OPS',
        'Operations',
        'العمليات',
        'Operations Department'
    FROM DUAL

) src
ON
(
    tgt.DEPARTMENT_CODE = src.DEPARTMENT_CODE
)

WHEN MATCHED THEN

    UPDATE SET
        tgt.DEPARTMENT_NAME    = src.DEPARTMENT_NAME,
        tgt.DEPARTMENT_NAME_AR = src.DEPARTMENT_NAME_AR,
        tgt.DESCRIPTION        = src.DESCRIPTION,
        tgt.ACTIVE_YN          = 'Y'

WHEN NOT MATCHED THEN

    INSERT
    (
        DEPARTMENT_CODE,
        DEPARTMENT_NAME,
        DEPARTMENT_NAME_AR,
        DESCRIPTION,
        ACTIVE_YN
    )
    VALUES
    (
        src.DEPARTMENT_CODE,
        src.DEPARTMENT_NAME,
        src.DEPARTMENT_NAME_AR,
        src.DESCRIPTION,
        'Y'
    );


COMMIT;
